services:
  db:
    image: postgres:17
    volumes: 
      - budget-cli-data:/varlib/postgresql/data
    restart: always
    env_file: "dev.env"
    ports: 
      - "8081:5432"

volumes: 
  budget-cli-data:
